//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Depthmap.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_TABLEVIEW                   101
#define IDD_SIDEBAR                     101
#define IDR_MAINFRAME                   128
#define IDR_GRAPHTYPE                   129
#define IDR_AGENTFRAME                  130
#define IDR_GRAPHTYPE2                  130
#define IDD_SPLASH                      131
#define IDR_EVAS                        131
#define IDR_GRAPHTYPE3                  131
#define IDR_GRAPHTYPE4                  132
#define IDC_HAND_CURSOR                 133
#define IDC_ZOOM_IN                     134
#define IDC_ZOOM_OUT                    135
#define IDC_FILL_CURSOR                 136
#define IDC_ERASE_CURSOR                137
#define IDB_NARROW                      143
#define IDB_STOCHATA                    144
#define IDD_WAIT_DIALOG                 146
#define IDD_GRID_DIALOG                 147
#define IDD_LICENCE_DIALOG              148
#define IDD_MAKE_GRAPH_DIALOG           149
#define IDB_SPLASH                      151
#define IDD_ANALYSIS_OPTIONS            153
#define IDD_ANALYSIS_OPTIONS_RESEARCH   154
#define IDB_UCL_LOGO                    168
#define IDB_COVER_FULL                  169
#define IDB_COVER_SEMI                  170
#define IDB_COVER_RAND                  171
#define IDD_MAKE_OPTIONS                172
#define IDC_PENCIL                      173
#define IDR_RESEARCH_TOOLBAR            174
#define IDD_EDIT_CONNECTIONS            177
#define IDD_COLOUR_SCALE                178
#define IDC_LINKCURSOR                  181
#define IDD_AGENT_SIM                   182
#define IDC_LINKCURSOR1                 182
#define IDD_AGENT_PROPERTIES            183
#define IDD_DIALOG_BAR                  185
#define IDD_FILE_EXPORT                 186
#define IDD_AGENT_SUMMARY               187
#define IDR_OLDTOOLS                    190
#define IDD_WALKER_SIM                  192
#define IDD_LAYERCHOOSER                193
#define IDB_STATEICONS                  195
#define IDD_PROMPTREPLACE               196
#define IDC_ERASE                       198
#define IDC_CROSSCURSOR                 199
#define IDD_AGENT_PROGRAMMER            200
#define IDC_SEED_CURSOR                 200
#define IDC_LINKCURSOR2                 201
#define IDC_MOVE_CURSOR                 202
#define IDB_SPLASH2                     204
#define IDD_EVOAGENT_SETUP              209
#define IDD_FEWESTOPTIONS               210
#define IDR_AGENT_TOOLBAR               211
#define IDB_ACCEPT                      213
#define IDB_REJECT                      214
#define IDR_COLUMN_TOOLBAR              215
#define IDD_AXIAL_ANALYSIS_OPTIONS      217
#define IDR_TEMP                        218
#define IDD_SEGMENT_ANALYSIS_OPTIONS    219
#define IDD_AXIALSEGMENTS_OPTIONS       220
#define IDR_COLUMN_EDITOR_TOOLBAR       221
#define IDR_COLUMN_EDITOR_TOOLBAR1      222
#define IDD_FILEPROPERTIES              223
#define IDR_COLUMN_EDITOR_TOOLBAR2      223
#define IDD_ATTRIBUTE_SUMMARY           224
#define IDB_SIDEICONS                   224
#define IDD_SCRIPT_DIALOG               225
#define IDD_INSERT_COLUMN               226
#define IDD_DIALOG_BAR1                 227
#define IDD_PUSH_DIALOG                 228
#define IDD_OVERRIDE_WIDTH_SIZE         230
#define IDR_3D_NAV                      232
#define IDD_AGENT_ANALYSIS              239
#define IDD_ATTRIBUTE_CHOOSER           240
#define IDD_COPY_ATTRIBUTES             241
#define IDR_POPUP_SIDEBAR_MAP           242
#define IDR_POPUP_SIDEBAR               242
#define IDD_RENAME_COLUMN               243
#define IDD_COLUMN_PROPERTIES           244
#define IDB_STATEICONS2                 246
#define IDR_MAP_TOOLBAR                 248
#define IDB_SIDEICONS2                  249
#define IDB_SIDETREEICONS               249
#define IDB_MAP_BAR_COLD                250
#define IDB_MAP_BAR_HOT                 251
#define IDR_POPUP_MAPBAR                252
#define IDB_COLUMNHEADERICONS           252
#define IDD_ALERT                       253
#define IDB_SIDEICONS3                  253
#define IDB_SIDELISTICONS               254
#define IDD_NEW_LAYER                   256
#define IDD_MAKE_LAYER                  259
#define IDD_LAYER_CHOOSER               260
#define IDD_DEPTHMAP_OPTIONS            261
#define IDR_MENU1                       262
#define IDR_EXTRA_EVENTS                262
#define IDD_FINDLOC                     263
#define IDD_SET_ATTR_VALUE              264
#define IDB_BITMAP2                     266
#define IDR_NON_MENU_COMMANDS           267
#define IDD_ISOVISTPATH                 268
#define IDD_CONVERT_SHAPES              270
#define IDD_TOPOMET                     272
#define IDC_DESCRIPTION                 1000
#define IDC_INFORMATION                 1001
#define IDC_MESSAGE                     1002
#define IDC_PROGRESS_BAR                1003
#define IDC_GRID_SNAP                   1004
#define IDC_GRID_OFFSETX                1004
#define IDC_GRID_SIZE                   1005
#define IDC_LICENCE_KEY                 1006
#define IDC_MID                         1006
#define IDC_PREFIX                      1007
#define IDC_SUFFIX                      1008
#define IDC_BUILD                       1009
#define IDC_RESOLUTION                  1011
#define IDC_VERSION                     1013
#define IDC_GLOBAL                      1027
#define IDC_LOCAL                       1028
#define IDC_RADIUS                      1029
#define IDC_EXPIRY_INFO                 1031
#define IDC_OPTIONS                     1036
#define IDC_CLIQUES                     1042
#define IDC_LICENCE_BOX                 1043
#define IDC_NAME_EDIT                   1046
#define IDC_ORGANIZATION_EDIT           1047
#define IDC_TYPE                        1059
#define IDC_RADIO2                      1060
#define IDC_RADIO3                      1061
#define IDC_RADIO4                      1062
#define IDC_SEL_TO_PIN                  1064
#define IDC_PIN_TO_SEL                  1065
#define IDC_RED_SLIDER                  1066
#define IDC_BLUE_SLIDER                 1067
#define IDC_RED_VALUE                   1068
#define IDC_BLUE_VALUE                  1069
#define IDC_SAVEAS                      1070
#define IDC_BROWSE                      1071
#define IDC_CHOICE                      1072
#define IDC_COLOR                       1075
#define IDC_COLOR2                      1076
#define IDC_BLUE                        1077
#define IDC_RED                         1078
#define IDC_VRLINK                      1079
#define IDC_COLOR3                      1079
#define IDC_VRLINK2                     1080
#define IDC_COLOR4                      1080
#define IDC_RELEASE_EPOCH               1081
#define IDC_RELEASE_ORDER               1082
#define IDC_STOP_SIM_EPOCH              1083
#define IDC_STOP_RELEASE_EPOCH          1084
#define IDC_CHECK_STOP_RELEASE          1085
#define IDC_CHECK_STOP_SIM              1086
#define IDC_NAME                        1087
#define IDC_AGENTS_DIE_EPOCH            1087
#define IDC_POSITION                    1088
#define IDC_CHECK_AGENTS_DIE            1088
#define IDC_SELECTED_ONLY               1088
#define IDC_TARGET                      1089
#define IDC_START_RECORD_EPOCH          1089
#define IDC_VIEW_SELECTOR               1091
#define IDC_CHECK_NEW_RECORD_COL        1092
#define IDC_VIEW_SELECTOR1              1092
#define IDC_EXPORT_TYPE                 1093
#define IDC_VIEW_SELECTOR2              1093
#define IDC_FOV                         1094
#define IDC_STEPS                       1095
#define IDC_PANIC                       1096
#define IDC_SIDESTEPS                   1097
#define IDC_COVERAGE                    1100
#define IDC_PATH_LENGTH                 1101
#define IDC_SEED                        1102
#define IDC_VISUAL                      1103
#define IDC_GUIDANCE_MECH               1105
#define IDC_GUIDANCE                    1106
#define IDC_AVOID_CROWDS                1107
#define IDC_GRAPH_OPTION2               1109
#define IDC_GRAPH_OPTION1               1110
#define IDC_MATRIX_OPTION               1111
#define IDC_PAFTL_LINK                  1112
#define IDC_GRID_OFFSETY                1113
#define IDC_SPIN_SPACING                1114
#define IDC_SPIN_OFFSETY                1115
#define IDC_SPIN_OFFSETX                1116
#define IDC_ALGORITHM                   1117
#define IDC_SPARKGRAPH                  1118
#define IDC_SHOP                        1119
#define IDC_LIFE                        1120
#define IDC_EDIT1                       1121
#define IDC_TRAIL_COUNT                 1121
#define IDC_MAXDIST                     1121
#define IDC_ORIGIN_LAYER                1121
#define IDC_ORGIN_LAYERS                1121
#define IDC_EDITX                       1121
#define IDC_LICENCE                     1121
#define IDC_EDIT2                       1122
#define IDC_ORIGIN_ATTRIBUTE            1122
#define IDC_CREATOR                     1122
#define IDC_LAYER_NAME                  1122
#define IDC_EDITY                       1122
#define IDC_VALUE                       1122
#define IDC_EDIT3                       1123
#define IDC_LAYERLIST                   1124
#define IDC_CREATE_PROGRAM              1124
#define IDC_VIEWNONE                    1125
#define IDC_AUTHOR                      1125
#define IDC_FRAMES                      1125
#define IDC_VIEWALL                     1126
#define IDC_LOCATION                    1126
#define IDC_FILE_VERSION                1127
#define IDC_FILESELECTOR                1130
#define IDC_FILE                        1131
#define IDC_REPLACE                     1132
#define ID_ADD                          1133
#define ID_REPLACE                      1134
#define IDC_PROGRAM                     1138
#define IDC_VARIABLE1                   1139
#define IDC_VARIABLE2                   1140
#define IDC_TOTAL_TASTE                 1142
#define IDC_SUMMARY                     1143
#define IDC_COPY                        1144
#define IDC_LAYERCOMBO                  1145
#define IDC_OUTPUT_TYPE                 1148
#define IDC_BACKGROUND                  1149
#define IDC_GATES                       1151
#define IDC_DIRECTIONAL                 1152
#define IDC_RADIUS2                     1153
#define IDC_ECOMORPH                    1155
#define IDC_EVOECOMORPH                 1156
#define IDC_LOGARITHMIC                 1157
#define IDC_BOUNDARYGRAPH               1158
#define IDC_EVOLVEAPPLY                 1159
#define IDC_FILENAME                    1161
#define IDC_RADIO1                      1162
#define IDC_FEWESTOPTION                1163
#define IDC_LAYER_SELECTOR              1164
#define IDC_LIST                        1168
#define IDC_REJECT                      1169
#define IDC_ACCEPT                      1170
#define IDC_EDIT                        1171
#define IDC_ANALYSIS_TYPE               1172
#define IDC_TULIP_BINS                  1173
#define IDC_REMOVE_STUBS                1174
#define IDC_PERCENTAGE_LENGTH           1175
#define IDC_TITLE                       1176
#define IDC_ORGANIZATION                1177
#define IDC_CREATE_DATE                 1178
#define IDC_RADIUS_TYPE                 1179
#define IDC_TYPE_ANGULAR                1180
#define IDC_TYPE_METRIC                 1181
#define IDC_TYPE_METRIC2                1182
#define IDC_SAVE                        1185
#define IDC_SCRIPT_EDIT                 1187
#define IDC_PUSH_VALUES                 1188
#define IDC_WEIGHTED                    1190
#define IDC_ATTRIBUTE_CHOOSER           1191
#define IDC_BLANK_COLUMN                1192
#define IDC_COLUMN_NAMES                1193
#define IDC_USE_ATTRIBUTE               1194
#define IDC_FORMULA                     1195
#define IDC_SELECTION_ONLY              1196
#define IDC_OVERRIDE                    1199
#define IDC_OVERRIDE_VALUE              1200
#define IDC_INCLUDE_RA                  1201
#define IDC_SIDEBAR_TREE                1202
#define IDC_LABEL                       1205
#define IDC_TIMESTEPS                   1207
#define IDC_RELEASE_RATE                1208
#define IDC_RELEASE_LOCATION            1209
#define IDC_ATTRIBUTE                   1211
#define IDC_TEXT                        1212
#define IDC_COLUMN_NAME                 1213
#define IDC_FORMULA_DESC                1214
#define IDC_OCCLUSION                   1215
#define IDC_RECORD_TRAILS               1217
#define IDC_READ_IT                     1219
#define IDC_ALERT_LINK                  1221
#define IDC_RESTRICT                    1225
#define IDC_LAYER_TYPE                  1226
#define IDC_HOWTO                       1229
#define IDC_COUNT                       1230
#define IDC_NAME_TEXT                   1233
#define IDC_FORMULA_NOTE                1234
#define IDC_REMOVE_STUBS_MORE           1237
#define IDC_LAYER                       1238
#define IDC_SHOW_RESEARCH_TOOLBAR       1239
#define IDC_CHECK1                      1240
#define IDC_KEEPORIGINAL                1240
#define IDC_SHOW_LINES                  1240
#define IDC_ATTRIBUTE_LIST              1241
#define IDC_SHOW_FILL                   1243
#define IDC_SHOW_CENTROIDS              1244
#define IDC_ATTRIBUTE_NAME              1246
#define IDC_PROMPT                      1247
#define IDC_APPLYTOALL                  1249
#define IDC_COPYRIGHT                   1250
#define IDC_COPYRIGHT_INFO              1251
#define IDC_CONVERSION_TYPE             1252
#define IDC_BAR9                        1253
#define IDC_TOPOLOGICAL                 1253
#define IDC_METRIC                      1254
#define ID_MOVE                         32771
#define ID_ZOOM                         32772
#define ID_FILL                         32773
#define ID_ERASE                        32774
#define ID_TOOLS_OPTIONS                32775
#define ID_TOOLS_RUN                    32776
#define ID_FILE_IMPORT                  32777
#define ID_FILE_EXPORT                  32778
#define ID_TOOLS_MAKE_GRAPH             32779
#define ID_IMPORT                       32781
#define ID_VIEW_MOVE                    32782
#define ID_VIEW_ZOOM                    32783
#define ID_EDIT_FILL                    32784
#define ID_EDIT_ERASE                   32785
#define ID_INDICATOR_POSITION           32786
#define ID_INDICATOR_DIMENSIONS         32787
#define ID_INDICATOR_POINTS             32788
#define ID_VIEW_ZOOM_IN                 32789
#define ID_VIEW_ZOOM_OUT                32790
#define ID_EDIT_SELECT                  32794
#define ID_VIEW_DUMMY                   32797
#define ID_TOOLS_ALLOCATEREFERENCES     32798
#define ID_EDIT_PENCIL                  32800
#define ID_EDIT_RANDOM                  32801
#define ID_EDIT_PENCIL2                 32801
#define ID_TOOL_PD                      32802
#define ID_EDIT_RANDOM2                 32803
#define ID_EDIT_PIN                     32805
#define ID_TOOLS_PD                     32806
#define ID_EDIT_CONNECTIONS             32807
#define ID_TOOLS_AA                     32808
#define ID_VIEW_COLOURRANGE             32809
#define ID_TOOLS_ADD_AGENT              32810
#define ID_MODE_ADD_AGENT               32811
#define ID_HELP_UPGRADELICENCE          32812
#define ID_HELP_MANUAL                  32813
#define ID_TOOLS_AL                     32815
#define ID_TOOLS_CANCEL_AGENTS          32816
#define ID_TOOLS_CLEAR_AGENTS           32817
#define ID_ADD_GATE                     32818
#define ID_TOOLS_CANCEL_AGENTS2         32819
#define ID_PUSH_TO_LAYER                32820
#define ID_WINDOW_FOREGROUND            32821
#define ID_TOOLS_CLEAR_AGENTS2          32821
#define ID_WINDOW_BACKGROUND            32822
#define ID_ADD_GATE2                    32822
#define ID_PUSH_TO_LAYER3               32823
#define ID_EDIT_SAVESCREEN              32824
#define ID_EDIT_GRID                    32825
#define ID_EDIT_FIXGRID                 32826
#define ID_VIEW_SHOWGRID                32827
#define ID_EDIT_FIXGRID2                32828
#define ID_MODE_MERGE                   32830
#define ID_MODE_JOIN                    32831
#define ID_VIEW_LINELAYERS              32837
#define ID_EDITFIX_FILL                 32839
#define ID_EDIT_FIXFILL                 32840
#define ID_EDIT_FIXFILL2                32841
#define ID_EDIT_ERASER                  32842
#define ID_EDIT_LINETOOL                32843
#define ID_EDIT_ERASER2                 32844
#define ID_FILL_SELECTION               32845
#define ID_EDIT_LINETOOL2               32845
#define ID_TOOLS_MPD                    32846
#define ID_TESTBUTTON                   32847
#define ID_PUSH_TO_LAYER2               32848
#define ID_EVOAGENT                     32849
#define ID_BINDISPLAY                   32850
#define ID_TOOLS_AL2                    32851
#define ID_TOOLS_AL3                    32852
#define ID_TOOLS_MAKE_FLM               32853
#define ID_TOOLS_RUN_ALM                32854
#define ID_TOOLS_RUN_AXA                32854
#define ID_TOOLS_RUN_FLM                32855
#define ID_VIEW_ALLLINEMAP              32856
#define ID_VIEW_FEWESTLINEMAP           32857
#define ID_VIEW_VGALAYERS_BRINGTOTOP    32860
#define ID_VIEW_VGALAYERS_SHOW          32861
#define ID_VIEW_AXIALLAYERS_SHOW        32862
#define ID_VIEW_AXIALLAYERS_BRINGTOTOP  32863
#define ID_VIEW_VGA_SHOW                32864
#define ID_VIEW_AXIAL_SHOW              32865
#define ID_VIEW_AXIAL_TOP               32866
#define ID_VIEW_VGA_TOP                 32867
#define ID_LINESTOAXIAL                 32874
#define ID_TOOLS_LINESTOAXIAL           32874
#define ID_VIEW_TABLE                   32875
#define ID_EDIT_COPYDATA                32876
#define ID_VIEW_DISPLAYTEXT             32877
#define ID_VIEW_CENTREVIEW              32878
#define ID_BUTTON32879                  32879
#define ID_BUTTON32880                  32880
#define ID_EDIT_SEMIFILL                32881
#define ID_HELP_GRAPH_VERSION           32882
#define ID_VIEW_SHOW_LINKS              32887
#define ID_TOOLS_AXIALTOSEG             32888
#define ID_TOOLS_RUN_SEG                32889
#define ID_ADD_COLUMN                   32891
#define ID_REMOVE_COLUMN                32893
#define ID_MAGIMIF                      32895
#define ID_BINDISTANCES                 32896
#define ID_FILE_PROPERTIES              32897
#define TOOLS_IMPORT                    32898
#define ID_TOOLS_IMPORT                 32899
#define ID_TOOLS_APD                    32900
#define ID_TOOLS_BOUNDARYTOAXIAL        32901
#define ID_TOOLS_AXIAL_MAKEGATES        32902
#define ID_VIEW_SUMMARY                 32903
#define ID_SWAP_COLOURS                 32908
#define ID_BUTTON32909                  32909
#define ID_NO                           32913
#define ID_RED_BUTTON                   32914
#define ID_TOOLS_AXIAL_OPEN_UNLINKS     32915
#define ID_TOOLS_AXIAL_SAVE_UNLINKS     32916
#define ID_TOOLS_AXIAL_CLEAR_LINKS      32918
#define ID_VIEW_SHAPE_SHOW              32919
#define ID_VIEW_SHAPE_TOP               32920
#define ID_UPDATE_COLUMN                32921
#define ID_TOOLS_POINT_CONVERTAXIALINTERSECTIONSTOVGAMAP 32925
#define ID_TOOLS_LINESTOSEG             32926
#define ID_BUTTON32927                  32927
#define ID_TOOLS_POINT_CONSHAPEMAP      32928
#define ID_TOOLS_AXIAL_CONVSHAPEMAP     32929
#define ID_VIEW_SCATTERPLOT             32930
#define ID_WINDOW_MAP                   32931
#define ID_BUTTON32933                  32933
#define ID_WINDOW_TABLE                 32934
#define ID_VIEW_LINEWIDTH               32935
#define ID_VIEW_POINTSIZE               32936
#define ID_TREND_LINE                   32938
#define ID_R_SQUARED                    32939
#define ID_VIEW_RSQUARED                32940
#define ID_VIEW_TREND_LINE              32941
#define ID_VIEW_COLOR                   32942
#define ID_WINDOW_3DVIEW                32943
#define ID_3D_ROT_VIEW                  32945
#define ID_ADD_AGENT                    32947
#define ID_3D_PAN                       32948
#define ID_3D_ZOOM                      32949
#define ID_3D_ROT                       32950
#define ID_3D_PAUSE                     32951
#define ID_AGENT_TRAILS                 32952
#define ID_TOOLS_AGENT_RUN              32954
#define ID_TOOLS_AGENT_LOAD_PROGRAM     32955
#define ID_BLAH                         32956
#define ID_TOOLS_LINE_LOADUNLINKSFROMFILE 32957
#define ID_TOOLS_LINE_LOADUNLINKS       32958
#define ID_REDTEST                      32959
#define ID_GREENTEST                    32960
#define ID_TOOLS_LINE_CONVSHAPEMAPE     32961
#define ID_TOOLS_SEGMENT_CONVSHAPEMAP   32962
#define ID_TOOLS_LINE_FROMSHAPEMAP      32963
#define ID_TOOLS_SEGMENT_FROMSHAPEMAP   32964
#define ID_POPUP_SIDEBAR_MAP_DELETE     32965
#define ID_POPUP_SIDEBAR_RENAME_MAP     32966
#define ID_POPUP_SIDEBAR_RENAME_ATTR    32968
#define ID_POPUP_SIDEBAR_DEL_ATTR       32969
#define ID_POPUP_SIDEBAR_MAP_RENAME     32970
#define ID_POPUP_SIDEBAR_ATTR_RENAME    32971
#define ID_POPUP_SIDEBAR_ATTR_DELETE    32972
#define ID_POPUP_SIDEBAR_ATTR_UPDATE    32973
#define ID_RENAME_COLUMN                32974
#define ID_SELECT_QUERY                 32975
#define ID_EDIT_QUERY                   32976
#define ID_VIEW_ORIGIN                  32977
#define ID_VIEW_EQUATION                32978
#define ID_MAKE_ISOVIST                 32979
#define ID_MODE_ISOVIST                 32980
#define ID_3D_PLAY_LOOP                 32981
#define ID_3D_FILLED                    32983
#define ID_SIDEBAR_ATTR_PROPERTIES      32985
#define ID_POPUP_SIDEBAR_PROPERTIES     32987
#define ID_POPUP_SIDEBAR_ATTR_PROPERTIES 32988
#define ID_COLUMN_PROPERTIES            32989
#define ID_HELP_TUTORIALS               32991
#define ID_MAPBAR_ZOOM_IN               32992
#define ID_MAPBAR_ZOOM_OUT              32993
#define ID_MAPBAR_FILL                  32995
#define ID_MAPBAR_SEMIFILL              32996
#define ID_MAPBAR_JOIN                  32997
#define ID_MAPBAR_UNJOIN                32998
#define ID_MODE_UNJOIN                  32999
#define ID_DEL_BUTTON                   33000
#define ID_PINKTEST                     33001
#define ID_MODE_HALFOVIST               33002
#define ID_MAPBAR_ISOVIST               33003
#define ID_MAPBAR_HALFOVIST             33004
#define ID_HELP_ALERTS                  33005
#define ID_LAYER_NEW                    33006
#define ID_LAYER_DELETE                 33007
#define ID_MAPBAR_LINE                  33009
#define ID_MAPBAR_POLYLINE              33010
#define ID_MAPBAR_BOX                   33011
#define ID_MAPBAR_POLYGON               33012
#define ID_EDIT_POLYGON                 33013
#define ID_HELP_SALA_MANUAL             33014
#define ID_LAYER_CONVERT                33015
#define ID_LAYER_CONVERT_DRAWING        33016
#define ID_VISIBILITY_RUNTHROUGHVISIONANALYSIS 33017
#define ID_THROUGH_VISION               33018
#define ID_VISIBILITY_STEPDEPTH         33019
#define ID_HELP_HIDERESEARCHTOOLS       33020
#define ID_EDIT_OPTIONS                 33021
#define ID_AGENTTOOLS_RUNAGENTANALYSIS  33022
#define ID_AGENTTOOLS_LOADAGENTPROGRAM  33023
#define ID_TEMP                         33024
#define ID_ANYTHING_SHOWRESEARCHTOOLBAR 33025
#define ID_SHOW_RESEARCHTOOLBAR         33026
#define ID_VIEW_FINDLOC                 33027
#define ID_VIEW_FINDLOCATION            33028
#define ID_MAP_CONVERTSELECTIONTOLAYER  33029
#define ID_SELECTION_TO_LAYER           33030
#define ID_EDIT_SELECT_TO_LAYER         33031
#define ID_TOOLS_IMPORT_TRACES          33033
#define ID_TOOLS_AGENTS_PLAY            33035
#define ID_TOOLS_AGENTS_PAUSE           33036
#define ID_TOOLS_AGENTS_STOP            33037
#define ID_DUMMY_PAUSEAGENTS            33038
#define ID_VIEW_ZOOMSEL                 33041
#define ID_VISIBILITY_MAKIEISOVISTPATH  33043
#define ID_TOOLS_ISOVISTPATH            33044
#define ID_SHOW_BINDISTANCES            33046
#define ID_MAP_CONVERT_SHAPES           33047
#define ID_CONVERT_MAP_SHAPES           33048
#define ID_SEGMENT_RUNTOPOLOGICALORMETRICANALYSIS 33049
#define ID_SEGMENT_TOPOLOGICALSTEPDEPTH 33050
#define ID_SEGMENT_METRICSTEPDEPTH      33051
#define ID_SEGMENT_TOPOMET              33052
#define ID_TOOLS_PD_TOPO                33053
#define ID_TOOLS_PD_METRIC              33054
#define ID_TOOLS_TOPOMET                33055
#define ID_SEGMENT_STEPDEPTH            33056
#define ID_SIDEBAR                      59394
#define ID_VIEW_LAYERS                  59419
#define ID_VIEW_ATTRIBUTES              59420
#define ID_VIEW_CONNECTIONS             59421
#define ID_VIEW_GATES                   59422
#define ID_VIEW_WALLS                   59423
#define ID_VIEW_BOUNDARIES              59423
#define ID_VIEW_ATTRACTORS              59424
#define ID_VIEW_AGENTS2                 59425
#define ID_VIEW_AGENTS                  59425

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        273
#define _APS_NEXT_COMMAND_VALUE         33057
#define _APS_NEXT_CONTROL_VALUE         1255
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
